site_name: بی‌اس‌دی فارسی
site_url: https://bsdfarsi.github.io
repo_url: https://github.com/bsdfarsi/bsdfarsi.github.io

theme:
  name: null
  custom_dir: theme

nav:
  - معرفی سیستم‌عامل DragonflyBSD: dragonflybsd.md
  - اولین رویداد (FreeBSD Day): index.md
  - مرام‌نامه جامعه: rules.md
  - تحلیل لایسنس (BSD vs GPL): license.md

extra_css:
  - css/main.css
