name: Deploy Custom MkDocs Platform
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install MkDocs Engine
        run: pip install mkdocs

      - name: Compile and Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
